from flask import Blueprint, current_app, make_response, request, jsonify
from database.db import get_db
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.units import cm
import io
from datetime import datetime

report_bp = Blueprint('report', __name__)


# ============================================================
# EXISTING — Violation Summary PDF Report
# ============================================================

@report_bp.route('/report/export')
def export_pdf():
    db = get_db(current_app.config['DATABASE'])

    total_assets = db.execute('SELECT COUNT(*) FROM assets').fetchone()[0]
    total_violations = db.execute('SELECT COUNT(*) FROM violations').fetchone()[0]

    violations = db.execute('''
        SELECT v.similarity, v.detected_at, a.name as asset_name
        FROM violations v
        JOIN assets a ON v.asset_id = a.id
        ORDER BY v.detected_at DESC
    ''').fetchall()

    db.close()

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    elements = []

    title_style = ParagraphStyle('title',
        fontSize=22, fontName='Helvetica-Bold',
        textColor=colors.HexColor('#4f46e5'), spaceAfter=6)
    sub_style = ParagraphStyle('sub',
        fontSize=10, fontName='Helvetica',
        textColor=colors.HexColor('#475569'), spaceAfter=20)

    elements.append(Paragraph('SportShield AI', title_style))
    elements.append(Paragraph(
        f'Violation Report — Generated {datetime.now().strftime("%d %b %Y, %H:%M")}',
        sub_style
    ))

    summary_data = [
        ['Metric', 'Value'],
        ['Total Registered Assets', str(total_assets)],
        ['Total Violations Detected', str(total_violations)],
        ['Report Generated', datetime.now().strftime('%d %b %Y %H:%M')],
    ]
    summary_table = Table(summary_data, colWidths=[10*cm, 6*cm])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#4f46e5')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#f8fafc'), colors.white]),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 0.5*cm))

    if violations:
        elements.append(Paragraph('Violation Log', ParagraphStyle('h2',
            fontSize=14, fontName='Helvetica-Bold',
            textColor=colors.HexColor('#0f172a'), spaceAfter=10, spaceBefore=10)))

        vdata = [['Asset Name', 'Similarity', 'Risk Level', 'Detected At']]
        for v in violations:
            sim = v['similarity']
            risk = 'CRITICAL' if sim >= 90 else 'HIGH' if sim >= 70 else 'MEDIUM' if sim >= 50 else 'LOW'
            vdata.append([v['asset_name'], f"{sim}%", risk, v['detected_at'][:16]])

        vtable = Table(vdata, colWidths=[6*cm, 3*cm, 3*cm, 5*cm])
        vtable.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#e11d48')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 9),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#fff1f2'), colors.white]),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
            ('PADDING', (0,0), (-1,-1), 7),
        ]))
        elements.append(vtable)

    elements.append(Spacer(1, 1*cm))
    elements.append(Paragraph(
        'This report was automatically generated by SportShield AI — Digital Asset Protection System.',
        ParagraphStyle('footer', fontSize=8, textColor=colors.HexColor('#94a3b8'))
    ))

    doc.build(elements)
    buf.seek(0)

    response = make_response(buf.read())
    response.headers['Content-Type'] = 'application/pdf'
    response.headers['Content-Disposition'] = \
        f'attachment; filename=sportshield_report_{datetime.now().strftime("%Y%m%d")}.pdf'
    return response


# ============================================================
# NEW — Auto DMCA Takedown Letter PDF
# ============================================================

@report_bp.route('/report/dmca/<int:violation_id>')
def generate_dmca(violation_id):
    """
    Generate a ready-to-send DMCA takedown letter for a specific violation.
    """
    db = get_db(current_app.config['DATABASE'])
    violation = db.execute('''
        SELECT v.id, v.similarity, v.detected_at, v.found_url,
               a.name as asset_name, a.filename as asset_filename
        FROM violations v
        JOIN assets a ON v.asset_id = a.id
        WHERE v.id = ?
    ''', (violation_id,)).fetchone()
    db.close()

    if not violation:
        return "Violation not found", 404

    from routes.blockchain import get_chain_stats, load_chain
    chain = load_chain()
    # Find matching blockchain block for evidence hash
    evidence_hash = "N/A"
    for block in chain:
        if (block.get('type') == 'VIOLATION' and
                block['data'].get('asset_name') == violation['asset_name']):
            evidence_hash = block['data'].get('evidence_hash', 'N/A')
            break

    sim = violation['similarity']
    risk = 'CRITICAL' if sim >= 90 else 'HIGH' if sim >= 70 else 'MEDIUM'
    detected_date = violation['detected_at'][:10] if violation['detected_at'] else datetime.now().strftime('%Y-%m-%d')
    found_url = violation['found_url'] or "[URL of infringing content]"

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            rightMargin=2.5*cm, leftMargin=2.5*cm,
                            topMargin=2*cm, bottomMargin=2*cm)

    elements = []

    # Styles
    org_style = ParagraphStyle('org',
        fontSize=20, fontName='Helvetica-Bold',
        textColor=colors.HexColor('#4f46e5'), spaceAfter=2)
    tagline_style = ParagraphStyle('tag',
        fontSize=9, fontName='Helvetica',
        textColor=colors.HexColor('#64748b'), spaceAfter=4)
    heading_style = ParagraphStyle('heading',
        fontSize=14, fontName='Helvetica-Bold',
        textColor=colors.HexColor('#0f172a'), spaceAfter=12, spaceBefore=16,
        alignment=1)  # center
    body_style = ParagraphStyle('body',
        fontSize=10, fontName='Helvetica',
        textColor=colors.HexColor('#1e293b'), spaceAfter=10, leading=16)
    bold_style = ParagraphStyle('bold',
        fontSize=10, fontName='Helvetica-Bold',
        textColor=colors.HexColor('#0f172a'), spaceAfter=6)
    footer_style = ParagraphStyle('footer',
        fontSize=8, fontName='Helvetica',
        textColor=colors.HexColor('#94a3b8'), alignment=1)

    # Header
    elements.append(Paragraph('🛡️ SportShield AI', org_style))
    elements.append(Paragraph('Digital Asset Protection System', tagline_style))
    elements.append(HRFlowable(width="100%", thickness=1,
                               color=colors.HexColor('#e2e8f0'), spaceAfter=16))

    # Date + reference
    elements.append(Paragraph(
        f'Date: {datetime.now().strftime("%d %B %Y")}',
        ParagraphStyle('date', fontSize=10, fontName='Helvetica',
                       textColor=colors.HexColor('#475569'), spaceAfter=4)
    ))
    elements.append(Paragraph(
        f'Reference No: DMCA-{violation_id:05d}-{datetime.now().strftime("%Y%m%d")}',
        ParagraphStyle('ref', fontSize=10, fontName='Helvetica',
                       textColor=colors.HexColor('#475569'), spaceAfter=20)
    ))

    # Title
    elements.append(Paragraph('DMCA TAKEDOWN NOTICE', heading_style))
    elements.append(Paragraph(
        'Pursuant to 17 U.S.C. § 512(c)(3) of the Digital Millennium Copyright Act',
        ParagraphStyle('sub_heading', fontSize=9, fontName='Helvetica',
                       textColor=colors.HexColor('#64748b'), alignment=1, spaceAfter=20)
    ))

    # Body
    elements.append(Paragraph('To Whom It May Concern,', body_style))

    elements.append(Paragraph(
        f'I, the undersigned, am an authorized representative of <b>SportShield AI</b>, '
        f'the lawful owner of the intellectual property described below. '
        f'I write to notify you of infringing activity occurring on your platform '
        f'and to request immediate removal of the infringing material.',
        body_style
    ))

    # Section 1 — Copyrighted Work
    elements.append(Paragraph('1. Identification of Copyrighted Work', bold_style))
    work_data = [
        ['Asset Name', violation['asset_name']],
        ['Asset File', violation['asset_filename']],
        ['Owner / Rights Holder', 'SportShield AI'],
        ['Protection Method', 'AI Fingerprinting + Blockchain Registration'],
    ]
    work_table = Table(work_data, colWidths=[6*cm, 10*cm])
    work_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#f1f5f9')),
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('PADDING', (0,0), (-1,-1), 8),
        ('ROWBACKGROUNDS', (0,0), (-1,-1), [colors.HexColor('#f8fafc'), colors.white]),
    ]))
    elements.append(work_table)
    elements.append(Spacer(1, 0.4*cm))

    # Section 2 — Infringing Material
    elements.append(Paragraph('2. Identification of Infringing Material', bold_style))
    infringe_data = [
        ['Infringing URL', found_url],
        ['Detection Date', detected_date],
        ['Similarity Score', f'{sim}% match'],
        ['Risk Level', risk],
        ['Detection Methods', 'pHash, dHash, aHash, SIFT/ORB (OpenCV), MobileNet AI'],
        ['Blockchain Evidence Hash', evidence_hash],
    ]
    infringe_table = Table(infringe_data, colWidths=[6*cm, 10*cm])
    infringe_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#fff1f2')),
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (1,1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#fecdd3')),
        ('PADDING', (0,0), (-1,-1), 8),
        ('ROWBACKGROUNDS', (0,0), (-1,-1), [colors.HexColor('#fff1f2'), colors.HexColor('#fef2f2')]),
        ('TEXTCOLOR', (1,2), (1,2), colors.HexColor('#e11d48')),
        ('FONTNAME', (1,2), (1,2), 'Helvetica-Bold'),
    ]))
    elements.append(infringe_table)
    elements.append(Spacer(1, 0.4*cm))

    # Section 3 — Good Faith Statement
    elements.append(Paragraph('3. Good Faith Statement', bold_style))
    elements.append(Paragraph(
        'I have a good faith belief that the use of the described material '
        'in the manner complained of is not authorized by the copyright owner, '
        'its agent, or the law.',
        body_style
    ))

    # Section 4 — Accuracy Statement
    elements.append(Paragraph('4. Statement of Accuracy', bold_style))
    elements.append(Paragraph(
        'The information in this notification is accurate, and under penalty of perjury, '
        'I am authorized to act on behalf of the owner of an exclusive right that is '
        'allegedly infringed.',
        body_style
    ))

    # Section 5 — Requested Action
    elements.append(Paragraph('5. Requested Action', bold_style))
    elements.append(Paragraph(
        'I hereby request that you immediately: (a) remove or disable access to the '
        'infringing material identified above, (b) notify the infringing party that '
        'the content has been removed due to a DMCA complaint, and (c) provide '
        'confirmation of removal to the contact address below.',
        body_style
    ))

    elements.append(Spacer(1, 0.5*cm))

    # Signature block
    elements.append(HRFlowable(width="100%", thickness=0.5,
                               color=colors.HexColor('#e2e8f0'), spaceAfter=12))
    elements.append(Paragraph('Sincerely,', body_style))
    elements.append(Paragraph(
        '<b>SportShield AI</b><br/>'
        'Digital Asset Protection System<br/>'
        f'Generated: {datetime.now().strftime("%d %B %Y, %H:%M")}<br/>'
        'Blockchain-verified evidence available upon request.',
        ParagraphStyle('sig', fontSize=10, fontName='Helvetica',
                       textColor=colors.HexColor('#1e293b'), leading=18, spaceAfter=20)
    ))

    elements.append(HRFlowable(width="100%", thickness=0.5,
                               color=colors.HexColor('#e2e8f0'), spaceAfter=8))
    elements.append(Paragraph(
        f'This DMCA notice was auto-generated by SportShield AI on '
        f'{datetime.now().strftime("%d %b %Y")}. '
        f'Violation ID: {violation_id} | Evidence Hash: {evidence_hash}',
        footer_style
    ))

    doc.build(elements)
    buf.seek(0)

    response = make_response(buf.read())
    response.headers['Content-Type'] = 'application/pdf'
    response.headers['Content-Disposition'] = \
        f'attachment; filename=DMCA_Takedown_{violation["asset_name"].replace(" ", "_")}_{datetime.now().strftime("%Y%m%d")}.pdf'
    return response
